server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bluemsun_blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: zhuxinyue
  server:
    servlet:
      encoding:
        enabled: true
        force: true
        charset: utf-8


mybatis:
  mapper-locations: classpath:com.bluemsunblog.dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
